const views=document.querySelectorAll('.view'),navButtons=document.querySelectorAll('[data-view]'),title=document.getElementById('pageTitle'),dialog=document.getElementById('dialog'),dialogContent=document.getElementById('dialogContent'),toast=document.getElementById('toast');
const pageTitles={home:'Günün güzel geçsin, <span>deniz.</span>',map:'Şehrini <span>keşfet.</span>',games:'Birlikte <span>oyna.</span>',memories:'Anıların <span>seninle.</span>',profile:'Senin <span>alanın.</span>'};
function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));navButtons.forEach(b=>b.classList.toggle('active',b.dataset.view===id));title.innerHTML=pageTitles[id];window.scrollTo({top:0,behavior:'smooth'});}
navButtons.forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view)));
function openDialog(html){dialogContent.innerHTML=html;dialog.showModal();}
document.querySelector('.close').addEventListener('click',()=>dialog.close());
document.getElementById('inviteButton').addEventListener('click',()=>openDialog('<p class="eyebrow">ARKADAŞLARINI ÇAĞIR</p><h2 class="dialog-title">Davet bağlantın hazır</h2><p class="dialog-copy">Bu bağlantıyı gönder; arkadaşların katıldığında birlikte oyun seçebilirsiniz.</p><input class="dialog-field" value="hatzone.app/davet/oyun-gecesi" readonly><button class="primary" id="copyInvite">Bağlantıyı kopyala</button>'));
document.addEventListener('click',e=>{if(e.target.id==='copyInvite'){navigator.clipboard?.writeText('hatzone.app/davet/oyun-gecesi');dialog.close();notify('Davet bağlantısı kopyalandı.');}if(e.target.id==='savePlace'){dialog.close();notify('Yeni yer haritana eklendi.');}if(e.target.id==='saveMemory'){dialog.close();notify('Anın paylaşıldı.');}});
document.getElementById('addPlace').addEventListener('click',()=>openDialog('<p class="eyebrow">YENİ YER</p><h2 class="dialog-title">Güzel bir yer paylaş</h2><input class="dialog-field" placeholder="Mekân adı"><input class="dialog-field" placeholder="Kısa notun"><button class="primary" id="savePlace">Paylaş</button>'));
document.getElementById('memoryButton').addEventListener('click',()=>openDialog('<p class="eyebrow">YENİ ANI</p><h2 class="dialog-title">Bugününden bir kare</h2><input class="dialog-field" type="file" accept="image/*"><input class="dialog-field" placeholder="Bu ana küçük bir not"><button class="primary" id="saveMemory">Anıyı paylaş</button>'));
document.querySelectorAll('.start-game').forEach(button=>button.addEventListener('click',()=>openDialog('<p class="eyebrow">PARTİ OYUNU</p><h2 class="dialog-title">'+button.dataset.game+' başlıyor!</h2><p class="dialog-copy">Davet bağlantını arkadaşlarınla paylaş. Herkes katıldığında ilk tur otomatik başlayacak.</p><button class="primary" id="copyInvite">Davet bağlantısı oluştur</button>')));
document.getElementById('themeButton').addEventListener('click',()=>{document.body.classList.toggle('dark');notify(document.body.classList.contains('dark')?'Koyu görünüm etkin.':'Açık görünüm etkin.');});
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600);}
