import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import {getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,onAuthStateChanged,updateProfile} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import {getFirestore,collection,addDoc,setDoc,doc,onSnapshot,query,orderBy,limit,serverTimestamp,increment,updateDoc} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
const app=initializeApp({apiKey:'AIzaSyDGKNKjAYvScio10swZ8FDT6uiY1gsxlXI',authDomain:'beyondscreen-7cdd2.firebaseapp.com',projectId:'beyondscreen-7cdd2',storageBucket:'beyondscreen-7cdd2.firebasestorage.app',messagingSenderId:'320897216507',appId:'1:320897216507:web:52a0a2f15c02f082ef655e'}),auth=getAuth(app),db=getFirestore(app),$=s=>document.querySelector(s);let user,isLogin=false;
document.body.insertAdjacentHTML('afterbegin','<section class="auth-screen" id="authScreen"><div class="auth-brand"><span class="brand-mark">H</span> hatzone</div><div class="auth-card"><p class="eyebrow">GERÇEK HAYATA BAĞLAN</p><h1 id="authTitle">Hatzone’a hoş geldin.</h1><form id="authForm"><label id="usernameRow">Kullanıcı adı<input id="username" required minlength="3" placeholder="ör. deniz"></label><label>E-posta<input id="email" required type="email" placeholder="ornek@mail.com"></label><label>Şifre<input id="password" required type="password" minlength="6" placeholder="En az 6 karakter"></label><button class="primary auth-submit" id="authSubmit">Hesap oluştur →</button></form><p class="auth-switch" id="authSwitch"></p></div></section>');
const esc=v=>{let e=document.createElement('span');e.textContent=v||'';return e.innerHTML},say=m=>{let e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)},name=()=>user.displayName||user.email.split('@')[0],modal=h=>{$('#dialogContent').innerHTML=h;$('#dialog').showModal()};
function authScreen(){$('#usernameRow').style.display=isLogin?'none':'grid';$('#authTitle').textContent=isLogin?'Tekrar hoş geldin.':'Hatzone’a hoş geldin.';$('#authSubmit').textContent=isLogin?'Giriş yap →':'Hesap oluştur →';$('#authSwitch').innerHTML=isLogin?'Hesabın yok mu? <button id="modeButton">Hesap oluştur</button>':'Zaten hesabın var mı? <button id="modeButton">Giriş yap</button>';$('#modeButton').onclick=()=>{isLogin=!isLogin;authScreen()}}
function data(){onSnapshot(query(collection(db,'places'),orderBy('createdAt','desc'),limit(12)),s=>{document.querySelectorAll('.remote-place').forEach(e=>e.remove());s.docs.forEach(d=>{let x=d.data(),e=document.createElement('article');e.className='place-card remote-place';e.innerHTML='<div class="place-image park"></div><div><strong>'+esc(x.name)+'</strong><p>“'+esc(x.note)+'”</p><small>İstanbul · '+esc(x.username)+'</small></div>';$(' .place-list').appendChild(e)})});onSnapshot(query(collection(db,'memories'),orderBy('createdAt','desc'),limit(18)),s=>{document.querySelectorAll('.remote-memory').forEach(e=>e.remove());s.docs.forEach(d=>{let x=d.data(),e=document.createElement('article');e.className='memory remote-memory';e.innerHTML='<div class="memory-photo photo-three"></div><div><p class="tag">'+esc(x.place).toUpperCase()+' · ANI</p><h3>'+esc(x.note)+'</h3></div>';$(' .memory-grid').appendChild(e)});document.querySelectorAll('.profile-stats strong')[0].textContent=s.size+2})}
document.querySelectorAll('[data-view]').forEach(e=>e.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===e.dataset.view))});$('.close').onclick=()=>$('#dialog').close();$('#themeButton').onclick=()=>document.body.classList.toggle('dark');
$('#authForm').onsubmit=async e=>{e.preventDefault();try{let mail=$('#email').value.trim(),pass=$('#password').value;if(isLogin)await signInWithEmailAndPassword(auth,mail,pass);else{let n=$('#username').value.trim(),r=await createUserWithEmailAndPassword(auth,mail,pass);await updateProfile(r.user,{displayName:n});await setDoc(doc(db,'users',r.user.uid),{username:n,gamesPlayed:0,createdAt:serverTimestamp()})}}catch(e){say(e.code==='auth/email-already-in-use'?'Bu e-posta ile zaten hesap var.':'Giriş veya kayıt başarısız.')}};
$('#inviteButton').onclick=()=>modal('<h2 class="dialog-title">Davet bağlantın hazır</h2><input class="dialog-field" value="'+location.origin+'/?invite=oyun-gecesi" readonly><button class="primary" id="copyInvite">Kopyala</button>');$('#addPlace').onclick=()=>modal('<h2 class="dialog-title">Güzel bir yer paylaş</h2><input class="dialog-field" id="placeName" placeholder="Mekân adı"><input class="dialog-field" id="placeNote" placeholder="Kısa notun"><button class="primary" id="savePlace">Paylaş</button>');$('#memoryButton').onclick=()=>modal('<h2 class="dialog-title">Yeni anı</h2><p class="dialog-copy">Fotoğraf paylaşımı için Storage gerekir; bu anı metin olarak kaydedilecek.</p><input class="dialog-field" id="memoryPlace" placeholder="Neredeydin?"><input class="dialog-field" id="memoryNote" placeholder="Notun"><button class="primary" id="saveMemory">Paylaş</button>');
document.querySelectorAll('.start-game').forEach(e=>e.onclick=async()=>{await updateDoc(doc(db,'users',user.uid),{gamesPlayed:increment(1)});modal('<h2 class="dialog-title">'+esc(e.dataset.game)+' başlıyor!</h2><p class="dialog-copy">İlk soru: Gruptaki en iyi yolculuk hikâyesini kim anlatır?</p>')});document.addEventListener('click',async e=>{if(e.target.id==='copyInvite'){await navigator.clipboard.writeText(location.origin+'/?invite=oyun-gecesi');$('#dialog').close();say('Davet bağlantısı kopyalandı.')}if(e.target.id==='savePlace'){let n=$('#placeName').value.trim(),t=$('#placeNote').value.trim();if(!n)return say('Mekân adı gerekli.');await addDoc(collection(db,'places'),{name:n,note:t,username:name(),ownerUid:user.uid,createdAt:serverTimestamp()});$('#dialog').close()}if(e.target.id==='saveMemory'){let p=$('#memoryPlace').value.trim(),n=$('#memoryNote').value.trim();if(!p||!n)return say('Yer ve not gerekli.');await addDoc(collection(db,'memories'),{place:p,note:n,username:name(),ownerUid:user.uid,createdAt:serverTimestamp()});$('#dialog').close()}});
$('.profile-card .soft').onclick=()=>signOut(auth);onAuthStateChanged(auth,u=>{user=u;if(u){$('#authScreen').classList.add('hidden');let n=name(),i=n[0].toUpperCase();$('.avatar').textContent=i;$('.profile-avatar').textContent=i;$('.profile-card h2').textContent=n;$('.profile-card > p').textContent='@'+n+' · İstanbul';data()}else{isLogin=true;$('#authScreen').classList.remove('hidden');authScreen()}});authScreen();
